package net.minenite.npcs.cognition;

public enum TalkWhy {
    WARN, ASK, LIE, DEFLECT, THREATEN, REASSURE, GREET, FILL_SILENCE,
    REQUEST_HELP, TRADE, GOSSIP, CONFIRM, CHALLENGE, APOLOGIZE, THANK,
    COMFORT, ARGUE, END_CONVERSATION, NONE
}
